{% set name = "hgdl" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lbl-camera/HGDL/archive/{{ version }}.tar.gz
  sha256: 20ac4254c291a58bb58a6c1d3cc74d7ab1139f3971812e29e9ab15f31e6d144c
  patches:
    - dep.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy
    - matplotlib-base
    - plotly
    - nbformat
    - dask-core >=2021.6.2
    - distributed >=2021.6.2
    - bokeh
    - paramiko
    - loguru

test:
  imports:
    - hgdl
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lbl-camera/HGDL
  summary: API for Distributed HPC Function Optimization
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
