{% set name = "hgdl" %}
{% set version = "2.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lbl-camera/HGDL/archive/{{ version }}.tar.gz
  sha256: 14683f9595bd4b5c35a0b4ddb2e922262510dbf9d05c7efbe73e12c72688e876

build:
  noarch: python
  script: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }} {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=3.9
    - wheel
    - scipy >=1.13.0,<1.14.dev0
    - numpy >=1.26.4,<1.27.dev0
    - dask-core =2024.5.0
    - distributed =2024.5.0
    - loguru

test:
  imports:
    - hgdl
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lbl-camera/HGDL
  summary: API for Distributed HPC Function Optimization
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
