{% set name = "hgdl" %}
{% set version = "2.3.3" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lbl-camera/HGDL/archive/{{ version }}.tar.gz
  sha256: 74cbeabd9d94e8445dceb3d2855590e4885a5f1201e16306cfdecdb40a79858c

build:
  noarch: python
  script: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }} {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - wheel
    - scipy >=1.16.0,<1.17.dev0
    - numpy >=2.2.6,<2.3.dev0
    - dask-core >=2025.5.1,<2025.6.dev0
    - distributed >=2025.5.1,<2025.6.dev0
    - loguru

test:
  imports:
    - hgdl
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/lbl-camera/HGDL
  summary: API for Distributed HPC Function Optimization
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
