{% set name = "hgdl" %}
{% set version = "2.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lbl-camera/HGDL/archive/{{ version }}.tar.gz
  sha256: d9ca64c978df2ccb0de7c26322b9824282593e9d612958cfb2dc87a031e659f9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  script: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }} {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=3.9
    - wheel
    - scipy >=1.13.0,<1.14.dev0
    - numpy >=1.26.4,<1.27.dev0
    - dask-core >=2024.5.0,<2024.6.dev0
    - distributed >=2024.5.0,<2024.6.dev0
    - loguru

test:
  imports:
    - hgdl
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lbl-camera/HGDL
  summary: API for Distributed HPC Function Optimization
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
